export default {
  width: 750,
  height: 800,
  backgroundColor: "#fff",
  debug: true,
  blocks: [{
    x: 0,
    y: 0,
    width: 750,
    height: 850,
    paddingLeft: 0,
    paddingRight: 0,
    borderWidth: 0,
    backgroundColor: "#EFF3F5",
    borderRadius: 0
  }, {
    x: 40,
    y: 40,
    width: 670,
    height: 770,
    paddingLeft: 0,
    paddingRight: 0,
    borderWidth: 0,
    backgroundColor: "#fff",
    borderRadius: 12
  }],
  texts: [{
    x: 80,
    y: 500,
    text: "【毛豆新车网】首付3000元起开新车！新车首付低、门槛低、月供低。",
    fontSize: 32,
    color: "#000",
    opacity: 1,
    baseLine: "middle",
    lineHeight: 48,
    lineNum: 2,
    textAlign: "left",
    width: 580,
    zIndex: 999
  }, {
    x: 80,
    y: 660,
    text: "长按扫描二维码关注毛豆新车服务号",
    fontSize: 24,
    color: "#666",
    opacity: 1,
    baseLine: "middle",
    textAlign: "left",
    lineHeight: 36,
    lineNum: 1,
    zIndex: 999
  }, {
    x: 80,
    y: 720,
    text: "分享来自 「 毛豆新车网 」",
    fontSize: 24,
    color: "#666",
    opacity: 1,
    baseLine: "middle",
    textAlign: "left",
    lineHeight: 36,
    lineNum: 1,
    zIndex: 999
  }],
  images: [{
    url: "https://sta.maodou.com/xinche_web/static/images/overlay_bg.ca348206.png",
    width: 670,
    height: 400,
    y: 40,
    x: 40,
    borderRadius: 12,
    zIndex: 10
  }, {
    url: "https://sta.maodou.com/xinche_web/static/images/ewm-public.883dd2cb.jpg",
    width: 110,
    height: 110,
    y: 645,
    x: 560,
    borderWidth: 0,
    zIndex: 10
  }],
  lines: [{
    startY: 605,
    startX: 80,
    endX: 670,
    endY: 606,
    width: 1,
    color: "#eee"
  }]
};